[package]
name = "cargo-outdated"
version = "0.1.0"
authors = ["Kevin K. <kbknapp@gmail.com>"]

[dependencies]
clap = "*"
toml = "*"
semver = "*"
tabwriter = "*"
tempdir = "*"

[dependencies.ansi_term]
version = "*"
optional = true

[features]
default = ["color"]
color = ["ansi_term"]
debug = []